In [1]:
import numpy as np
import pandas as pd


In [4]:
'''
to make sample csv data file
df = pd.DataFrame(np.random.random((15,25)))
df.to_csv("test.csv",index=False)
'''

'\nto make sample csv data file\ndf = pd.DataFrame(np.random.random((15,25)))\ndf.to_csv("test.csv",index=False)\n'

In [2]:
def get_feature_matrix(file_path):
    df = pd.read_csv(file_path, header=0)
    #print(df)
    n_data = len(df.index)
    n_feature = len(df.columns)
    #print(n_data,n_feature)
    '''
    res = np.zeros((n_data, n_feature))

    for i in range(0,n_feature):
        res[:,i] = np.array(df.iloc[:,i])
    return res
    '''
    res = df.values
    return res

In [3]:
'''
df = pd.read_csv('test.csv', header=0)
res = np.zeros((15,25)) #dumb 
res[:,1] = np.array(df.iloc[:,1])
#print(df.iloc[:,1])
'''

"\ndf = pd.read_csv('test.csv', header=0)\nres = np.zeros((15,25)) #dumb \nres[:,1] = np.array(df.iloc[:,1])\n#print(df.iloc[:,1])\n"

In [7]:
mat = get_feature_matrix("../data/randomtest.csv")
len(mat[1,:])

25

In [82]:
mat.mean(axis=0)
mat - mat.mean(axis=0)
np.delete(mat,1,1)

array([[ 0.19516616,  0.68600533,  0.36343979,  0.8800926 ,  0.55287371,
         0.45938718,  0.01620561,  0.63462582,  0.10164633,  0.40655   ,
         0.35955377,  0.43913272,  0.20684399,  0.53729024,  0.20275462,
         0.06843351,  0.05382463,  0.6077778 ,  0.26389082,  0.17861733,
         0.67565529,  0.65447774,  0.96281883,  0.09869557],
       [ 0.43682131,  0.42863177,  0.53121182,  0.78285426,  0.89408929,
         0.70746886,  0.16983539,  0.6300726 ,  0.06031075,  0.56479152,
         0.03321906,  0.65433339,  0.91220651,  0.82970839,  0.78086343,
         0.26416246,  0.75806179,  0.6525081 ,  0.99983962,  0.04212188,
         0.84697543,  0.46435275,  0.50470931,  0.69812813],
       [ 0.06054085,  0.92474132,  0.57955491,  0.60529364,  0.57243094,
         0.32455584,  0.13896875,  0.36462129,  0.37195557,  0.53148464,
         0.34543243,  0.41319499,  0.49167176,  0.0204535 ,  0.06051272,
         0.09604028,  0.84979956,  0.52870893,  0.38475641,  0.02893577,
  

In [16]:
def get_output(file_path):
    """
    file_path: path to a file in the same format as in the Kaggle competition

    Return: an n x 1 numpy array where n is the number of examples in the file.
            The array must contain the Output column values of the file
    """
    df = pd.read_csv(file_path,header=0)
    res = np.array(df.iloc[:,len(df.columns)-1])
    return res

In [71]:
Y = get_output('../data/randomtest.csv')
print(Y - Y.mean())
np.random.rand(3)
np.random.rand(3)/np.random.rand(3)


[-0.39324034  0.20619222  0.44081531  0.37037751 -0.27797581 -0.32931249
  0.37771907 -0.26443624  0.11662967  0.06817944 -0.12325327  0.12039567
  0.12458522  0.02550645 -0.46218241]


array([ 1.66283742,  1.71931574,  0.55055361])

In [64]:
def get_cost(W,X,Y):
    n = len(X[1,:])
    m = len(Y)
    cost = 0
    for i in range(0,m):
        cost += (sum(W*X[i]) - Y[i])**2
    cost = cost/(2*n)
    
    return cost

In [67]:
def do_gradient_descent(X,Y):
    #both X,Y are numpy array
    n = len(X[1,:]) #num of features
    m = len(Y) #num of samples
    X_mean = X.mean(axis=0)
    Y_mean = Y.mean()
    
    #recentering the data
    X = X - X_mean
    Y = Y - Y_mean
    #hard coded alpha
    alpha = 0.01
    
    #the weight vector initialised
    W = 100*np.random.rand(n)
    W_ = np.zeros(n)
    
    #my epsilon
    eps = 0.001
    
    step = 0
    norm_diff_w = np.linalg.norm(W-W_)
    while(norm_diff_w > eps): 
        step += 1
        for k in range(0,n):
            dJ_dwk = 0
            for i in range(0,m):
                dJ_dwk += (sum(W*X[i,:])-Y[i])*X[i,k]
            dJ_dwk = dJ_dwk/n
            W_[k] = W[k] - alpha*dJ_dwk
        temp = W
        W = W_
        W_ = temp
        J = get_cost(W,X,Y)
        norm_diff_w = np.linalg.norm(W-W_)
        print('step={0}, J={1}, norm of diff of W={2}'.format(step,J,norm_diff_w))

In [92]:
#loading the data
tr = get_feature_matrix('../data/train.csv')
f = len(tr[1,:])
X = tr[:,0:f-1]
Y = tr[:,f-1]
#np.delete(X,1,1) #for deleting time stamps
X = np.delete(X,1,1)

#sanitizing the data
Y_max = Y.max()
X_maxs = X.max(axis = 0)
Y = Y/Y_max
X = X/X_maxs

In [94]:
Y

array([0.3516483516483517, 0.4065934065934066, 0.06593406593406594, ...,
       0.03296703296703297, 0.054945054945054944, 0.054945054945054944], dtype=object)

In [95]:
do_gradient_descent(X,Y)

step=1, J=323827.2289015876, norm of diff of W=95.58656439259728
step=2, J=181358.31147617006, norm of diff of W=42.225784132263534
step=3, J=117948.72995026594, norm of diff of W=27.02054839242268
step=4, J=81272.48249924685, norm of diff of W=20.292003629219607
step=5, J=58314.818413462795, norm of diff of W=15.96673670238289
step=6, J=43314.68582981363, norm of diff of W=12.852276405930422
step=7, J=33158.224302389324, norm of diff of W=10.535393157877744
step=8, J=26055.121286225625, norm of diff of W=8.779761877849731
step=9, J=20939.425666279865, norm of diff of W=7.427264456382464
step=10, J=17156.727297070367, norm of diff of W=6.3684450703463105
step=11, J=14293.171670770782, norm of diff of W=5.5267376638449
step=12, J=12079.449807302612, norm of diff of W=4.848111508468444
step=13, J=10335.559857559703, norm of diff of W=4.293988941213465
step=14, J=8938.222047023819, norm of diff of W=3.8364018936080133
step=15, J=7801.149085898763, norm of diff of W=3.454708796590583
step=

step=122, J=6.106246128890201, norm of diff of W=0.04402022522452371
step=123, J=5.92753446327174, norm of diff of W=0.042615431156844574
step=124, J=5.760034861213205, norm of diff of W=0.041256677085391574
step=125, J=5.603034944575263, norm of diff of W=0.03994239072088385
step=126, J=5.455868335737985, norm of diff of W=0.038671056837942426
step=127, J=5.317911625747546, norm of diff of W=0.03744121502326369
step=128, J=5.188581547451716, norm of diff of W=0.036251457522450486
step=129, J=5.067332339327585, norm of diff of W=0.03510042718063037
step=130, J=4.953653286737404, norm of diff of W=0.03398681547226898
step=131, J=4.84706642830696, norm of diff of W=0.03290936061584316
step=132, J=4.74712441600534, norm of diff of W=0.031866845769269264
step=133, J=4.6534085183217915, norm of diff of W=0.03085809730221342
step=134, J=4.565526756695117, norm of diff of W=0.029881983141615585
step=135, J=4.483112166050453, norm of diff of W=0.028937411186958244
step=136, J=4.405821170946453

step=239, J=3.231449744256176, norm of diff of W=0.001097421958742419
step=240, J=3.231338310989835, norm of diff of W=0.001063798641812535
step=241, J=3.2312336005301514, norm of diff of W=0.0010312089612075533
step=242, J=3.2311352066370684, norm of diff of W=0.0009996209890123717
